apiVersion: v1
kind: Service
metadata:
  name: '${parameters.app_name}'
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: '${parameters.app_name}'
  type: LoadBalancer
